  backend:
#{{hosted}}#
    image: {{org}}/{{project}}-backend:{{tag}}
#{{endhosted}}#
#{{local}}#
    build:
      context: ./backend
      dockerfile: ./Dockerfile.local
#{{endlocal}}#
    networks:
      - proxy
      - {{network_name}}
    command: bash -c "pm2-runtime start app.js"
    env_file:
      - ./envs/nodejs
    environment:
      - VIRTUAL_HOST={{backend}}{{domain}}
    volumes:
        - ./images:/app/public/images
#{{local}}#
        - ./backend:/app
        - /app/node_modules
    command: /bin/bash -c "yarn && yarn dev"
#{{endlocal}}#
    expose:
      - 80
