# Backend {{tag_upper}} NodeJS build
  backend-build:
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Dockerhub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile.{{tag}}
          push: true
          tags: {{org}}/{{project}}-backend:{{tag}}
          build-args: build_mode={{tag}}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
# Backend {{tag_upper}} NodeJS build end
