  pgadmin:
    user: root
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    env_file:
      - ./envs/pgadmin
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    ports:
      - "5050:80"
    networks:
      - {{network_name}}
      - proxy
    environment:
      - VIRTUAL_HOST={{pgadmin}}{{domain}}
      - LETSENCRYPT_HOST={{pgadmin}}{{domain}}
      - LETSENCRYPT_EMAIL={{email}}
    restart: unless-stopped
