  frontend:
    container_name: {{project}}-frontend
#{{hosted}}#
    image: {{org}}/{{project}}-frontend:{{tag}}
#{{endhosted}}#
#{{local}}#
    build:
      context: ./frontend
      dockerfile: ./frontend/Dockerfile.local
#{{endlocal}}#
    ports:
      - "8080:8080"
    environment:
      - VIRTUAL_HOST={{frontend}}{{domain}}
      - LETSENCRYPT_HOST={{frontend}}{{domain}}
      - LETSENCRYPT_EMAIL={{email}}
    labels:
      - io.portainer.accesscontrol.teams={{team}}
    networks:
      - proxy
      - {{project}}
